name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node-version: [18.x, 20.x, 22.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          # No lockfile yet; disable dependency caching to avoid errors.

      - name: Install dependencies
        run: npm install

      - name: Lint
        run: npm run lint

      - name: Prettier check
        run: npm run format

      - name: Type check and build
        run: npm run build

      - name: Test
        env:
          CI: true
        run: npm test -- --reporter=dot
